# Generated by Django 4.1.2 on 2022-11-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
    ]
